### ISSUE TITLE
bug(linter): some text in js file cause panic (byte index 8 is not a char boundary)

### ISSUE THREAD

**Issue by hirohe** [oxc-project/oxc#1671]
a js file contains line `console.error('\x1B[41;37mpackage.json文件没有改动，禁止提交package-lock.json \x1B[0m');`, the file is utf-8 and has ANSI escape sequences and zh-cn characters.

when execute the oxlint command:

```shell
oxlint -D all
```

it panic with message:

```shell
thread '<unnamed>' panicked at crates/oxc_linter/src/rules/unicorn/escape_case.rs:67:45:
byte index 55 is not a char boundary; it is inside '交' (bytes 54..57) of `'\x1B[41;37mpackage.json文件没有改动，禁止提交package-lock.json \x1B[0m'`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

oxlint version is `0.0.20`

**Comment by hirohe** [comment]
run with `RUST_BACKTRACE =full` outputs:

```shell
thread '<unnamed>' panicked at crates/oxc_linter/src/rules/unicorn/escape_case.rs:67:45:
byte index 55 is not a char boundary; it is inside '交' (bytes 54..57) of `'\x1B[41;37mpackage.json文件没有改动，禁止提交package-lock.json \x1B[0m'`
stack backtrace:
   0:        0x1005e447c - __mh_execute_header
   1:        0x10037dfec - __mh_execute_header
   2:        0x1005c3650 - __mh_execute_header
   3:        0x1005e7ce8 - __mh_execute_header
   4:        0x1005e7910 - __mh_execute_header
   5:        0x1005e87d8 - __mh_execute_header
   6:        0x1005e8370 - __mh_execute_header
   7:        0x1005e82dc - __mh_execute_header
   8:        0x1005e82d0 - __mh_execute_header
   9:        0x10064432c - __mh_execute_header
  10:        0x10038344c - __mh_execute_header
  11:        0x1006447e4 - __mh_execute_header
  12:        0x1004469ac - __mh_execute_header
  13:        0x100485618 - __mh_execute_header
  14:        0x100464948 - __mh_execute_header
  15:        0x10046104c - __mh_execute_header
  16:        0x100461240 - __mh_execute_header
  17:        0x10045eeac - __mh_execute_header
  18:        0x100461240 - __mh_execute_header
  19:        0x10045eeac - __mh_execute_header
  20:        0x100461240 - __mh_execute_header
  21:        0x10045eeac - __mh_execute_header
  22:        0x100461240 - __mh_execute_header
  23:        0x10045eeac - __mh_execute_header
  24:        0x1003df664 - __mh_execute_header
  25:        0x100658744 - __mh_execute_header
  26:        0x1005153ec - __mh_execute_header
  27:        0x1005150e4 - __mh_execute_header
  28:        0x1005e9a6c - __mh_execute_header
  29:        0x185f65034 - __pthread_joiner_wake
```

**Comment by Boshen** [comment]
Marking as good first issue for anyone who wants to write this using proper Rust iterators, probably with `let mut chars = s.chars()`, `.len_utf8()`, `peekable` and friends.

https://github.com/oxc-project/oxc/blob/d719af473c5ccf18d0b9177d97e081451ea40041/crates/oxc_linter/src/rules/unicorn/escape_case.rs#L55-L63

**Comment by Boshen** [comment]
cc original author @RiESAEX and 🦶 🔫 killer @camc314 .

**Comment by RiESAEX** [comment]
I should use index in bytes instead of in char, just calculate it in another variable.
but I don't know how to do this in a easy with iterator.
