### ISSUE TITLE
[playground|@oxc/oxc_wasm] Some code break the REPL

### ISSUE THREAD

**Issue by leaysgur** [oxc-project/oxc#2559]
I'm not sure which layer is the root cause, so I report things as they are.

To reproduce:

- Visit https://oxc-project.github.io/oxc/playground/
  - Private mode recommended
- Remove placeholders and paste these lines
```js
function foo() {}
declare function foo() {}
```
- See REPL stop working

Devtools console reports:

```
update listener: RuntimeError: unreachable
    at oxc_wasm_bg-DeC5fkkx.wasm:0x1bbc2f
    at oxc_wasm_bg-DeC5fkkx.wasm:0x25337f
    at oxc_wasm_bg-DeC5fkkx.wasm:0x232c4b
    at oxc_wasm_bg-DeC5fkkx.wasm:0x97eca
    at oxc_wasm_bg-DeC5fkkx.wasm:0x1a9f45
    at Ew.run (playground-fNXad_Yn.js:25:3578)
    at ui.run (playground-fNXad_Yn.js:44:3867)
    at ui.updateView (playground-fNXad_Yn.js:46:355)
    at ui.runOxc (playground-fNXad_Yn.js:44:1696)
    at playground-fNXad_Yn.js:44:1776
```
```
Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at Mw.i.wbg.__wbindgen_throw (playground-fNXad_Yn.js:25:9271)
    at oxc_wasm_bg-DeC5fkkx.wasm:0x28856d
    at oxc_wasm_bg-DeC5fkkx.wasm:0x28857b
    at oxc_wasm_bg-DeC5fkkx.wasm:0x254224
    at oxc_wasm_bg-DeC5fkkx.wasm:0x24e98d
    at oxc_wasm_bg-DeC5fkkx.wasm:0x1bdbcc
    at Ew.getDiagnostics (playground-fNXad_Yn.js:25:3246)
    at ui.updateDiagnostics (playground-fNXad_Yn.js:44:2477)
    at Vc.delay (playground-fNXad_Yn.js:44:1541)
    at playground-fNXad_Yn.js:11:46833
```

Once this happens, this code is saved to LocalStorage... which means the REPL can never be used again.

To workaroud, 

- Open DevTools > Applications > Storage > Local storage
- Remove `playgroud.code` key
- Re-visit REPL URL without `?code=...`

**Comment by Boshen** [comment]
@Dunqing crashing on this line

https://github.com/oxc-project/oxc/blob/d9cc429d4a23c55330dbee0f7d353a3195737156/crates/oxc_linter/src/rules/oxc/only_used_in_recursion.rs#L141
