### ISSUE TITLE
[npm oxlint] SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by 2096903746** [oxc-project/oxc#4602]
Although oxlint does not depend on Node.js, the npm package encounters syntax errors in lower versions of Node.js (v10.24.1). Could you downgrade the code here to make it compatible with the lower version of Node.js?

```
/node_modules/oxlint/bin/oxlint:94

let binPath = PLATFORMS[platform]?.[arch]?.[isMusl() ? "musl" : "gnu"];
                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by Boshen** [comment]
The file to be changed: https://github.com/oxc-project/oxc/blob/main/npm/oxlint/bin/oxlint
