### ISSUE TITLE
Panic `attempt to multiply with overflow` in `crates/oxc_regular_expression/src/body_parser/parser.rs`

### ISSUE THREAD

**Issue by qarmin** [oxc-project/oxc#5257]
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
/{99999999999999999999
```

command
```
timeout -v 100 oxlint -D all -D nursery --import-plugin --jsdoc-plugin --jest-plugin --vitest-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin TEST___FILE.js --fix
```

App was compiled with nightly rust compiler to be able to use address sanitizer
On Ubuntu 24.04, the commands to compile were:
```
rustup default nightly
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

export RUST_BACKTRACE=1
export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
export ASAN_OPTIONS=symbolize=1
RUSTFLAGS="-Zsanitizer=address" cargo +nightly build --target x86_64-unknown-linux-gnu
```

cause this
```
thread '<unnamed>' panicked at crates/oxc_regular_expression/src/body_parser/parser.rs:1679:21:
attempt to multiply with overflow
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/16760059/compressed.zip)

**Comment by leaysgur** [comment]
Would you please elaborate how to reproduce?

For my env(macOS), I don't see any errors.

```
# cd path/to/attached/js/file/location

❯ npx oxlint --version
Version: 0.9.0

❯ npx oxlint

  × Unterminated regular expression
   ╭─[regexp_IDX_9_RAND_84279508860295221049537_minimized_572.js:1:1]
 1 │ /{99999999999999999999
   · ───────────────────────
   ╰────

Finished in 2ms on 1 file with 93 rules using 8 threads.
Found 0 warnings and 1 error.
```

This only happens with the Rust nightly build?

**Comment by qarmin** [comment]
Panics are only visible in debug build
I can reproduce when installing app via
```
cargo install --git https://github.com/oxc-project/oxc.git oxlint --locked --debug
```
and using all parameters from first post

**Comment by camc314** [comment]
stack backtrace
```
thread '<unnamed>' panicked at crates/oxc_regular_expression/src/body_parser/parser.rs:1679:21:
attempt to multiply with overflow
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_const::panic_const_mul_overflow
   3: oxc_regular_expression::body_parser::parser::PatternParser::consume_decimal_digits
   4: oxc_regular_expression::body_parser::parser::PatternParser::consume_quantifier
   5: oxc_regular_expression::body_parser::parser::PatternParser::parse_extended_atom
   6: oxc_regular_expression::body_parser::parser::PatternParser::parse_term
   7: oxc_regular_expression::body_parser::parser::PatternParser::parse_alternative
   8: oxc_regular_expression::body_parser::parser::PatternParser::parse_disjunction
   9: oxc_regular_expression::body_parser::parser::PatternParser::parse
  10: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_regex_pattern
  11: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_literal_regexp::{{closure}}
  12: core::bool::<impl bool>::then
  13: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_literal_regexp
  14: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_primary_expression
  15: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_member_expression_or_higher
  16: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_lhs_expression_or_higher
  17: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_update_expression
  18: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_unary_expression_or_higher
  19: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_binary_expression_or_higher
  20: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_assignment_expression_or_higher
  21: oxc_parser::js::expression::<impl oxc_parser::ParserImpl>::parse_expr
  22: oxc_parser::js::statement::<impl oxc_parser::ParserImpl>::parse_expression_or_labeled_statement
  23: oxc_parser::js::statement::<impl oxc_parser::ParserImpl>::parse_statement_list_item
  24: oxc_parser::js::statement::<impl oxc_parser::ParserImpl>::parse_directives_and_statements
  25: oxc_parser::ParserImpl::parse_program
  26: oxc_parser::ParserImpl::parse
  27: oxc_parser::parser_parse::<impl oxc_parser::Parser>::parse
  28: oxc_linter::service::Runtime::process_source
  29: oxc_linter::service::Runtime::process_path
  30: oxc_linter::service::LintService::run::{{closure}}
  31: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume
  32: <&rayon::iter::par_bridge::IterParallelProducer<Iter> as rayon::iter::plumbing::UnindexedProducer>::fold_with
  33: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  34: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
  35: rayon_core::join::join_context::call_a::{{closure}}
  36: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: std::panicking::try::do_call
  38: ___rust_try
  39: std::panicking::try
  40: std::panic::catch_unwind
  41: rayon_core::unwind::halt_unwinding
  42: rayon_core::join::join_context::{{closure}}
  43: rayon_core::registry::in_worker
  44: rayon_core::join::join_context
  45: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  46: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
  47: rayon_core::join::join_context::call_a::{{closure}}
  48: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  49: std::panicking::try::do_call
  50: ___rust_try
  51: std::panicking::try
  52: std::panic::catch_unwind
  53: rayon_core::unwind::halt_unwinding
  54: rayon_core::join::join_context::{{closure}}
  55: rayon_core::registry::in_worker
  56: rayon_core::join::join_context
  57: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  58: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
  59: rayon_core::join::join_context::call_a::{{closure}}
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  61: std::panicking::try::do_call
  62: ___rust_try
  63: std::panicking::try
  64: std::panic::catch_unwind
  65: rayon_core::unwind::halt_unwinding
  66: rayon_core::join::join_context::{{closure}}
  67: rayon_core::registry::in_worker
  68: rayon_core::join::join_context
  69: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  70: rayon::iter::plumbing::bridge_unindexed_producer_consumer::{{closure}}
  71: rayon_core::join::join_context::call_a::{{closure}}
  72: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  73: std::panicking::try::do_call
  74: ___rust_try
  75: std::panicking::try
  76: std::panic::catch_unwind
  77: rayon_core::unwind::halt_unwinding
  78: rayon_core::join::join_context::{{closure}}
  79: rayon_core::registry::in_worker
  80: rayon_core::join::join_context
  81: rayon::iter::plumbing::bridge_unindexed_producer_consumer
  82: rayon::iter::plumbing::bridge_unindexed
  83: <rayon::iter::par_bridge::IterBridge<Iter> as rayon::iter::ParallelIterator>::drive_unindexed
  84: <rayon::iter::map_with::MapWith<I,T,F> as rayon::iter::ParallelIterator>::drive_unindexed
  85: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<()> for ()>::from_par_iter
  86: rayon::iter::ParallelIterator::collect
  87: rayon::iter::ParallelIterator::for_each_with
  88: oxc_linter::service::LintService::run
  89: <oxlint::lint::LintRunner as oxlint::runner::Runner>::run::{{closure}}
  90: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  91: std::panicking::try::do_call
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Rayon: detected unexpected panic; aborting
zsh: abort      RUST_BACKTRACE=1 ./target/debug/oxlint -D all
```

**Comment by leaysgur** [comment]
Thank you! Now I can see panic.

```sh
cd apps/oxlint
echo '/{99999999999999999999' > test.js
cargo run test.js
```

I think there are two bugs here:

- `/{123` is not a valid RegExp, but `oxc_parser` attempts to parse it as RegExp
  - Shouldn’t it instead report an error like unterminated regular expression?
- Even with a valid pattern like `/a{999999999999999999}/`, `oxc_regular_expression` panics
  - It should report an error like Number is too large instead of panicking.

I will try to fix the latter case.

@Boshen Could you please take a look at the former case? Or is this behavior intended?

**Comment by leaysgur** [comment]
It seems fixes are merged now. 

@qarmin  Thanks for the reporting!
