### ISSUE TITLE
oxlint vscode extension crashing on launch

### ISSUE THREAD

**Issue by orta** [oxc-project/oxc#7434]
Hello there, 

These are the logs which happen when the extension boots up on my codebase:

```
2024-11-23 08:27:36.537 [info] [2024-11-23T08:27:36Z INFO  oxc_language_server] initialize: Options { run: OnType, enable: true, config_path: ".eslintrc" }
[2024-11-23T08:27:36Z INFO  oxc_language_server] language server version: "0.0.1"

2024-11-23 12:54:24.158 [info] [Error - 12:54:24] Server process exited with code 0.
2024-11-23 12:54:24.537 [info] [2024-11-23T12:54:24Z INFO  oxc_language_server] initialize: Options { run: OnType, enable: true, config_path: ".eslintrc" }
[2024-11-23T12:54:24Z INFO  oxc_language_server] language server version: "0.0.1"

2024-11-23 12:54:39.056 [info] [2024-11-23T12:54:39Z INFO  oxc_language_server] initialize: Options { run: OnType, enable: true, config_path: "oxlint.json" }
[2024-11-23T12:54:39Z INFO  oxc_language_server] language server version: "0.0.1"

2024-11-23 12:54:39.152 [info] thread 'main' panicked at /Users/runner/work/oxc/oxc/crates/oxc_index/src/indexing.rs:38:10:
index out of bounds: the len is 0 but the index is 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-11-23 12:54:39.191 [info] [Error - 12:54:39] Server process exited with code 0.
2024-11-23 12:54:39.191 [info] [Error - 12:54:39] Client oxc: connection to server is erroring.
Cannot call write after a stream was destroyed
2024-11-23 12:54:39.191 [info] [Error - 12:54:39] Request textDocument/codeAction failed.
```

Maybe useful?

```
2024-11-23 13:11:29.500 [info] [Error - 13:11:29] Updating trace failed with error
2024-11-23 13:11:29.500 [info] Error: Cannot call write after a stream was destroyed
	at _write (node:internal/streams/writable:489:11)
	at Writable.write (node:internal/streams/writable:508:10)
	at /Users/orta/.vscode/extensions/oxc.oxc-vscode-0.13.0-darwin-arm64/out/main.js:31:14071
	at new Promise (<anonymous>)
	at Ha.write (/Users/orta/.vscode/extensions/oxc.oxc-vscode-0.13.0-darwin-arm64/out/main.js:31:13992)
	at ls.doWrite (/Users/orta/.vscode/extensions/oxc.oxc-vscode-0.13.0-darwin-arm64/out/main.js:3:1625)
	at /Users/orta/.vscode/extensions/oxc.oxc-vscode-0.13.0-darwin-arm64/out/main.js:3:1524
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processImmediate (node:internal/timers:454:9)
```

If it's important, I upgraded to 0.13 a bit earlier:

```
❯ yarn why oxlint
└─ puzzmo-monorepo@workspace:.
   └─ oxlint@npm:0.13.0 (via npm:^0.13.0)
```

I tested with an `oxlint.json`  (turning on the experimental react dept) and without, same crash

**Comment by Boshen** [comment]
cc @Sysix @nrayburn-tech

**Comment by Boshen** [comment]
> /Users/runner/work/oxc/oxc/crates/oxc_index/src/indexing.rs:38:10:

This is probably coming from a new lint rule, cc @camc314 as well.

**Comment by camc314** [comment]
ahhh i know why, will fix

**Comment by Boshen** [comment]
Thank you for reporting the issue, hope it's fixed in the latest https://github.com/oxc-project/oxc/releases/tag/oxlint_v0.13.1 release.
