### ISSUE TITLE
vscode: Language Server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by Sysix** [oxc-project/oxc#8023]
I deleted a File with Source Control (CTRL + SHIFT + G) and then after a while I got a notification.
This file does not exists anymore and he still wants to revalidate it.

Here are the logs:

```
2024-12-19 17:04:35.243 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.243 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/test.ts",
        "languageId": "typescript",
        "version": 1,
        "text": ""
    }
}


2024-12-19 17:04:35.243 [info] thread 'main' panicked at crates/oxc_language_server/src/linter.rs:237:60:
Failed to read "/home/sysix/dev/eslint-plugin-oxlint/test.ts"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-12-19 17:04:35.411 [info] [Error - 5:04:35 PM] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-12-19 17:04:35.411 [info] [Error - 5:04:35 PM] Server process exited with code 0.
```

<details><summary>Better log:</summary>
<p>

````
2024-12-19 17:04:34.919 [info] [Trace - 5:04:34 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:34.919 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/test.ts",
        "languageId": "typescript",
        "version": 1,
        "text": ""
    }
}


2024-12-19 17:04:34.919 [info] thread 'main' panicked at crates/oxc_language_server/src/linter.rs:237:60:
Failed to read "/home/sysix/dev/eslint-plugin-oxlint/test.ts"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-12-19 17:04:35.060 [info] [Info  - 5:04:35 PM] Connection to server got closed. Server will restart.
2024-12-19 17:04:35.060 [info] true
2024-12-19 17:04:35.063 [info] [Trace - 5:04:35 PM] Sending request 'initialize - (0)'.
2024-12-19 17:04:35.063 [info] Params: {
    "processId": 2116,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.96.0"
    },
    "locale": "en",
    "rootPath": "/home/sysix/dev/eslint-plugin-oxlint",
    "rootUri": "file:///home/sysix/dev/eslint-plugin-oxlint",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "foldingRange": {
                "refreshSupport": true
            },
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode",
                        "data"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true,
                "rangesSupport": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "settings": {
            "run": "onType",
            "enable": true,
            "configPath": ".oxlintrc.json"
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/sysix/dev/eslint-plugin-oxlint",
            "name": "eslint-plugin-oxlint"
        }
    ]
}


2024-12-19 17:04:35.063 [info] [Error - 5:04:35 PM] Server process exited with code 0.
2024-12-19 17:04:35.081 [info] [2024-12-19T16:04:35Z INFO  oxc_language_server] initialize: Options { run: OnType, enable: true, config_path: ".oxlintrc.json" }
[2024-12-19T16:04:35Z INFO  oxc_language_server] language server version: "0.0.1"

2024-12-19 17:04:35.088 [info] [Trace - 5:04:35 PM] Received response 'initialize - (0)' in 25ms.
2024-12-19 17:04:35.088 [info] Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": {
            "codeActionKinds": [
                "quickfix"
            ]
        },
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        }
    },
    "serverInfo": {
        "name": "oxc"
    }
}


2024-12-19 17:04:35.088 [info] [Trace - 5:04:35 PM] Sending notification 'initialized'.
2024-12-19 17:04:35.088 [info] Params: {}


2024-12-19 17:04:35.089 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.089 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/scripts/traverse-rules.ts",
        "languageId": "typescript",
        "version": 488,
        "text": "import { execSync } from 'node:child_process';\nimport { ignoreCategories, ignoreScope } from './constants.js';\n\nfunction readFilesFromCommand(): Rule[] {\n  // do not handle the exception\n  const oxlintOutput = execSync(`npx oxlint --rules --format=json`, {\n    encoding: 'utf8',\n    stdio: 'pipe',\n  });\n\n  // do not handle the exception\n  return JSON.parse(oxlintOutput);\n}\n\nexport interface Rule {\n  value: string;\n  scope: string;\n  category: string;\n}\n\nexport function traverseRules(): Rule[] {\n  const rules = readFilesFromCommand();\n\n  return rules.filter(\n    (rule) =>\n      !ignoreCategories.has(rule.category) && !ignoreScope.has(rule.scope)\n  );\n}\n"
    }
}


2024-12-19 17:04:35.089 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.089 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/scripts/generate.ts",
        "languageId": "typescript",
        "version": 9,
        "text": "import fs from 'node:fs';\nimport path from 'node:path';\nimport { RulesGenerator, RulesGrouping } from './rules-generator.js';\nimport { ConfigGenerator } from './config-generator.js';\nimport { traverseRules } from './traverse-rules.js';\n\nconst __dirname = new URL('.', import.meta.url).pathname;\n\nconst successResultArray = traverseRules();\n\nconst rulesGenerator = new RulesGenerator(successResultArray);\nconst configGenerator = new ConfigGenerator(successResultArray);\n\nconst generateFolder = path.resolve(__dirname, '..', `src/generated`);\n\nif (!fs.existsSync(generateFolder)) {\n  fs.mkdirSync(generateFolder);\n}\n\nconst promises = [rulesGenerator, configGenerator].map(async (generator) => {\n  generator.setRulesGrouping(RulesGrouping.SCOPE);\n  await generator.generateRules(generateFolder);\n  generator.setRulesGrouping(RulesGrouping.CATEGORY);\n  await generator.generateRules(generateFolder);\n});\n\nawait Promise.all(promises);\n"
    }
}


2024-12-19 17:04:35.089 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.089 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/test.ts",
        "languageId": "typescript",
        "version": 1,
        "text": ""
    }
}


2024-12-19 17:04:35.089 [info] thread 'main' panicked at crates/oxc_language_server/src/linter.rs:237:60:
Failed to read "/home/sysix/dev/eslint-plugin-oxlint/test.ts"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-12-19 17:04:35.089 [info] [Trace - 5:04:35 PM] Received notification 'textDocument/publishDiagnostics'.
2024-12-19 17:04:35.089 [info] Params: {
    "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/scripts/traverse-rules.ts",
    "diagnostics": [],
    "version": 488
}


2024-12-19 17:04:35.214 [info] [Info  - 5:04:35 PM] Connection to server got closed. Server will restart.
2024-12-19 17:04:35.214 [info] true
2024-12-19 17:04:35.217 [info] [Trace - 5:04:35 PM] Sending request 'initialize - (0)'.
2024-12-19 17:04:35.217 [info] Params: {
    "processId": 2116,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.96.0"
    },
    "locale": "en",
    "rootPath": "/home/sysix/dev/eslint-plugin-oxlint",
    "rootUri": "file:///home/sysix/dev/eslint-plugin-oxlint",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "foldingRange": {
                "refreshSupport": true
            },
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode",
                        "data"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true,
                "rangesSupport": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "settings": {
            "run": "onType",
            "enable": true,
            "configPath": ".oxlintrc.json"
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/sysix/dev/eslint-plugin-oxlint",
            "name": "eslint-plugin-oxlint"
        }
    ]
}


2024-12-19 17:04:35.217 [info] [Error - 5:04:35 PM] Server process exited with code 0.
2024-12-19 17:04:35.236 [info] [2024-12-19T16:04:35Z INFO  oxc_language_server] initialize: Options { run: OnType, enable: true, config_path: ".oxlintrc.json" }
[2024-12-19T16:04:35Z INFO  oxc_language_server] language server version: "0.0.1"

2024-12-19 17:04:35.242 [info] [Trace - 5:04:35 PM] Received response 'initialize - (0)' in 25ms.
2024-12-19 17:04:35.242 [info] Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": {
            "codeActionKinds": [
                "quickfix"
            ]
        },
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        }
    },
    "serverInfo": {
        "name": "oxc"
    }
}


2024-12-19 17:04:35.242 [info] [Trace - 5:04:35 PM] Sending notification 'initialized'.
2024-12-19 17:04:35.242 [info] Params: {}


2024-12-19 17:04:35.243 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.243 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/scripts/traverse-rules.ts",
        "languageId": "typescript",
        "version": 488,
        "text": "import { execSync } from 'node:child_process';\nimport { ignoreCategories, ignoreScope } from './constants.js';\n\nfunction readFilesFromCommand(): Rule[] {\n  // do not handle the exception\n  const oxlintOutput = execSync(`npx oxlint --rules --format=json`, {\n    encoding: 'utf8',\n    stdio: 'pipe',\n  });\n\n  // do not handle the exception\n  return JSON.parse(oxlintOutput);\n}\n\nexport interface Rule {\n  value: string;\n  scope: string;\n  category: string;\n}\n\nexport function traverseRules(): Rule[] {\n  const rules = readFilesFromCommand();\n\n  return rules.filter(\n    (rule) =>\n      !ignoreCategories.has(rule.category) && !ignoreScope.has(rule.scope)\n  );\n}\n"
    }
}


2024-12-19 17:04:35.243 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.243 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/scripts/generate.ts",
        "languageId": "typescript",
        "version": 9,
        "text": "import fs from 'node:fs';\nimport path from 'node:path';\nimport { RulesGenerator, RulesGrouping } from './rules-generator.js';\nimport { ConfigGenerator } from './config-generator.js';\nimport { traverseRules } from './traverse-rules.js';\n\nconst __dirname = new URL('.', import.meta.url).pathname;\n\nconst successResultArray = traverseRules();\n\nconst rulesGenerator = new RulesGenerator(successResultArray);\nconst configGenerator = new ConfigGenerator(successResultArray);\n\nconst generateFolder = path.resolve(__dirname, '..', `src/generated`);\n\nif (!fs.existsSync(generateFolder)) {\n  fs.mkdirSync(generateFolder);\n}\n\nconst promises = [rulesGenerator, configGenerator].map(async (generator) => {\n  generator.setRulesGrouping(RulesGrouping.SCOPE);\n  await generator.generateRules(generateFolder);\n  generator.setRulesGrouping(RulesGrouping.CATEGORY);\n  await generator.generateRules(generateFolder);\n});\n\nawait Promise.all(promises);\n"
    }
}


2024-12-19 17:04:35.243 [info] [Trace - 5:04:35 PM] Sending notification 'textDocument/didOpen'.
2024-12-19 17:04:35.243 [info] Params: {
    "textDocument": {
        "uri": "file:///home/sysix/dev/eslint-plugin-oxlint/test.ts",
        "languageId": "typescript",
        "version": 1,
        "text": ""
    }
}


2024-12-19 17:04:35.243 [info] thread 'main' panicked at crates/oxc_language_server/src/linter.rs:237:60:
Failed to read "/home/sysix/dev/eslint-plugin-oxlint/test.ts"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2024-12-19 17:04:35.411 [info] [Error - 5:04:35 PM] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-12-19 17:04:35.411 [info] [Error - 5:04:35 PM] Server process exited with code 0.
````

</p>
</details>

**Comment by Sysix** [comment]
closing. will be released in the next version. thanks!
